### PR TITLE
Update assetgraph to version 5

### PR DESCRIPTION
**Pull request by chrisguttandin**
This pull request updates assetgraph to version 5. I did this because I realized that the version of acorn that assetgraph at version 4 uses can't parse modern JavaScript syntax like the spread operator.

I order to get hyperlink working with assetgraph v5, I had to remove the compatibility check. It used some private methods of assetgraph which are not in place anymore after the update.

Please let me know if you have an idea how I could reintroduce the compatibility check or if there is anything else I need to do to make this pull request mergeable.

### CODE REVIEW

**Comment by papandreou** [comment]
Hi Chris,

Thanks for looking into this! I meant to try to tackle the assetgraph 5 upgrade as part of https://github.com/Munter/hyperlink/pull/143, but never really got around to it. I agree that updating outside of that PR would be worth it for the new features alone now that we got that JS parser upgrade in.

I'll look into it as soon as I get the chance, will try to lend a hand with the compatibility checks.

**Comment by chrisguttandin** [comment]
Alright, please let me know if there is anything I can do.

**Comment by papandreou** [comment]
@chrisguttandin, I found a way to reintroduce the compatibility check, fixed for next release. Thanks again for the contribution! :tada:

@Munter, can you help with getting a new version published?

**Comment by Munter** [comment]
@papandreou Great job on adding back the compatibility check and at the same time reducing its annoyance level!

Thanks for the contribution @chrisguttandin 

I've released https://github.com/Munter/hyperlink/releases/tag/v4.1.0

**Comment by chrisguttandin** [comment]
Many thanks for the quick response @papandreou and @Munter.

**Pull request merged**
